### ISSUE TITLE
arco CSS import overriding my own CSS rules

### ISSUE THREAD

**Issue by thijs-qv** [zalify/easy-email#240]
The theme is imported as a side effect import:
```
import '@arco-themes/react-easy-email-theme/css/arco.css';
```

This overrides some of my own styles I'm using in my app, since the styles are loaded globally. Is there a way to make the component use CSS from a namespace import instead so I can use CSS modules to locally scope the style?

**Comment by m-Ryan** [comment]
Sorry, there is no good solution to this problem, most UI frameworks come with global styles

**Comment by thijs-qv** [comment]
aww shucks
Thanks for the response, if I figure something out to solve this I'll post it here.

**Comment by rajathawsg** [comment]
hey @thijs-qv, are you able to give a small code example of the "descendant operator" solution you came up with? thanks!

**Comment by thijs-qv** [comment]
I don’t have the code in front of me atm (taking a bit of leave) but I think I added another selector so the styles were not overwriting my styles any more

https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator

**Comment by rajathawsg** [comment]
Thanks @thijs-qv, found a solution for my case with your idea.

For anyone else having the same issue (with tailwind), this is how i solved it.

**Steps**

Install postcss-prefix-selector (`npm i postcss-prefix-selector`)

Update the postcss config (`postcss.config.js`) with the below config and add any prefix (eg: `.app-email-editor-container`)
```js
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    "postcss-prefix-selector": {
      prefix: ".app-email-editor-container",
      includeFiles: ["arco.css"],
      transform(prefix, selector) {
        if (!selector.startsWith(".")) {
          return selector.replace(/^([^\s]*)/, `$1 ${prefix}`);
        }

        return selector;
      },
    },
  },
};
```

Wrap your email editor/provider with a div and add the prefix class
```html
<div className="app-email-editor-container">
  <EmailEditorProvider
    data={initialValues}
    height={"calc(100vh - 72px)"}
    autoComplete
    dashed={false}
    ...
</div>
```

**Explanation**

In the postcss-prefix-selector transform method, i have replaced any selector that is not a class (doesnt start with a "." which means they are some sort of global tag selector, etc...)
```js
transform(prefix, selector) {
  if (!selector.startsWith(".")) {
    return selector.replace(/^([^\s]*)/, `$1 ${prefix}`);
  }

  return selector;
}
```
This way since all the global styles in the email style sheet are prefixed, so only the elements inside the wrapper div is affected by the styles.
