### ISSUE TITLE
<Table> component not selectable in editor (except via Layers tab)

### ISSUE THREAD

**Issue by thijs-qv** [zalify/easy-email#346]
I have added a custom block which returns a `<Table>` as described in this issue: https://github.com/zalify/easy-email/issues/100
I have problems selecting this block in the editor window. It seems to take up the full width, and then later it is not selectable any more, except through the `Layers` tab, only the page and the wrapper can be selected but not the custom block itself.

![custom_table_1](https://github.com/zalify/easy-email/assets/52537741/36777321-88cc-42ae-9a0f-88de22b15d17)
![custom_table_2](https://github.com/zalify/easy-email/assets/52537741/25c5a9bb-1dfa-44c8-b11c-b1badf34cff7)

**Comment by m-Ryan** [comment]
Can you show your code? Someone has used Table before, but they didn't mention this issue.
https://github.com/zalify/easy-email/issues/204

**Comment by thijs-qv** [comment]
I'm returning the same thing as in the example:
```
const {Section, Column,Text, Table} = components;
<Table>
  {`
  <tr style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <th style="padding: 0 15px 0 0;">Year</th>
    <th style="padding: 0 15px;">Language</th>
    <th style="padding: 0 0 0 15px;">Inspired from</th>
  </tr>
  <tr  style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <td style="padding: 0 15px 0 0;">1995</td>
    <td style="padding: 0 15px;">PHP</td>
    <td style="padding: 0 0 0 15px;">C, Shell Unix</td>
  </tr>
  <tr  style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <td style="padding: 0 15px 0 0;">1995</td>
    <td style="padding: 0 15px;">JavaScript</td>
    <td style="padding: 0 0 0 15px;">Scheme, Self</td>
  </tr>
  `}
</Table>
```

**Comment by thijs-qv** [comment]
Apparently I did something wrong while adding the custom component. I've re-added it as a "default" component and it seems to be working fine now.

**Comment by dipak-tech-aher** [comment]
Hi @m-Ryan im also using same code but seems to be im not able to move my table from editor canvas since its not selectable

![image](https://github.com/user-attachments/assets/b19eb8ce-666c-4089-ba1a-5d8e091becf2)

here is my code snippet for my customblock

// import { IBlock, IBlockData, BasicType, components } from 'easy-email-core';
// import { CustomBlocksType } from '../constants';
// import React from 'react';
// import { merge } from 'lodash';

// const { Section, Column, Image, Button } = components;

// export type ICustomHeader = IBlockData<
//   {
//     'background-color': string;
//     'text-color': string;
//   },
//   {
//     buttonText: string;
//     imageUrl: string
//   }
// >;

// export const MyFirstBlock: IBlock = {
//   name: 'My first block',
//   type: CustomBlocksType.MY_FIRST_BLOCK,
//   create(
//     payload
//   ) {
//     const defaultData: ICustomHeader = {
//       type: CustomBlocksType.MY_FIRST_BLOCK,
//       data: {
//         value: {
//           buttonText: 'Got it',
//           imageUrl: 'https://assets.maocanhua.cn/10dada65-c4fb-4b1f-837e-59a1005bbea6-image.png'
//         },
//       },
//       attributes: {
//         'background-color': '#4A90E2',
//         'text-color': '#ffffff',
//       },
//       children: [],
//     };
//     return merge(defaultData, payload);
//   },
//   validParentType: [BasicType.PAGE, BasicType.WRAPPER],
//   render(data: ICustomHeader) {
//     const { imageUrl, buttonText } = data.data.data.value;
//     const attributes = data.data.attributes;

//     const instance = (
//       <Section padding="20px">
//         <Column>
//           <Image padding="0px 0px 0px 0px" width="100px" src={imageUrl} />
//           <Button background-color={attributes['background-color']} color={attributes['text-color']} href="#">
//             {buttonText}
//           </Button>
//         </Column>
//       </Section>
//     )
//     return instance;
//   },
// };

// export { Panel } from './Panel'

import { IBlock, IBlockData, BasicType, components } from "easy-email-core";
import { CustomBlocksType } from "../constants";
import React from "react";
import { merge } from "lodash";

const { Section, Column, Text, Table } = components;

export type ICustomTextBox = IBlockData<
  {
    "border-color": string;
    "border-width": string;
    "border-style": string;
    padding: string;
    "text-color": string;
  },
  {
    text: string;
  }
>;

export const MyFirstBlock: IBlock = {
  name: "Custom Text Box",
  type: CustomBlocksType.MY_FIRST_BLOCK,
  create(payload) {
    const defaultData: ICustomTextBox = {
      type: CustomBlocksType.MY_FIRST_BLOCK,
      data: {
        value: {
          text: "Your text here",
        },
      },
      attributes: {
        "border-color": "#000000",
        "border-width": "1px",
        "border-style": "solid",
        padding: "10px",
        "text-color": "#000000",
      },
      children: [],
    };
    return merge(defaultData, payload);
  },
  validParentType: [BasicType.PAGE, BasicType.WRAPPER],
  render(data: ICustomTextBox) {
    const { text } = data.data.data.value;
    const attributes = data.data.attributes;

    const instance = (
      <Section padding="20px">
        <Column>
          <Table>
            {`
  <tr style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <th style="padding: 0 15px 0 0;">Year</th>
    <th style="padding: 0 15px;">Language</th>
    <th style="padding: 0 0 0 15px;">Inspired from</th>
  </tr>
  <tr  style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <td style="padding: 0 15px 0 0;">1995</td>
    <td style="padding: 0 15px;">PHP</td>
    <td style="padding: 0 0 0 15px;">C, Shell Unix</td>
  </tr>
  <tr  style="border:1px solid #ecedee;text-align:left;padding:15px 0;">
    <td style="padding: 0 15px 0 0;">1995</td>
    <td style="padding: 0 15px;">JavaScript</td>
    <td style="padding: 0 0 0 15px;">Scheme, Self</td>
  </tr>
  `}
          </Table>
        </Column>
      </Section>
    );
    return instance;
  },
};

export { Panel } from "./Panel";
